### ISSUE TITLE
Cinnamon theme issues

### ISSUE THREAD

**Issue by natanvarga** [schemar/solarc-theme#14]
The latest cinnamon updates broke the cinnamon theme. Some screenshots attached show what I mean. 
![screenshot from 2017-01-26 00-49-40](https://cloud.githubusercontent.com/assets/6820797/22314438/a970b60c-e361-11e6-9366-942c0f737bc7.png)
![screenshot from 2017-01-26 00-49-47](https://cloud.githubusercontent.com/assets/6820797/22314439/a9aa7784-e361-11e6-86d2-990b63de5814.png)

**Comment by schemar** [comment]
OK, I will have to pull upstream in. I cannot promise by when I can do that.

**Comment by schemar** [comment]
Can you please check if the issue still exists with the latest version?

**Comment by natanvarga** [comment]
Seems fixed. Thank you very much, appreciate it!

**Comment by schemar** [comment]
Awesome 🎉
