### ISSUE TITLE
“Close” button; contrast

### ISSUE THREAD

**Issue by skalyan91** [schemar/solarc-theme#15]
In the Solarc-dark and Solarc-darker theme, the window-closing button has a white cross (like in the light Solarc and Arc themes). It should have a dark cross (like in the Arc-dark and Arc-darker themes).

Also, it might be good if there were more contrast between the text and background colors (especially in the dark themes). Currently, I find the text somewhat harder to read than in the Arc themes.

Thanks.

**Comment by schemar** [comment]
This might be fixed once upstream is pulled in. I am not sure when I can do that.

**Comment by schemar** [comment]
Can you please check if the issue still exists with the latest version?

**Comment by skalyan91** [comment]
Yes, the close button still has a light cross in the dark themes, and the text contrast is still low.

I notice the close buttons look OK in the screenshots. I wonder if it's just an issue with Unity vs. Gnome Shell.

**Comment by skalyan91** [comment]
It looks like `/common/unity/close.svg` has an opaque (light-grey) cross, whereas the other SVGs and PNGs for the close button all have a transparent cross.

**Comment by schemar** [comment]
Ahhh, then maybe I am missing that exact colour when replacing. Do you want to have a look at [solarize.sh](https://github.com/apheleia/solarc-theme/blob/master/solarize.sh)?
If not I will do it as soon as I have time, cannot give you any promises, though.

**Comment by skalyan91** [comment]
The color of the cross in `/common/unity/close.svg` appears to be `#f8f8f9`. There is no reference to that color in `solarize.sh`. Maybe the SVG needs to be changed?

**Comment by schemar** [comment]
`solarize.sh` works in a way where it replaces the original colours with the specified one. To fix your cross, you could add the colour you mentioned and its replacement.

You would add the Arc colour under `# Arc colors` ▶️ `## SVG`.
Then you would add the arc colour to the end of the array `ARC_COLORS` and add the proper replacement to the end of the array `SOLARIZED_COLORS`.

Then run the script `solarize.sh` and re-install the theme.

If you don't want to or cannot install the theme from git, I can later take care of it, please let me know.

**Comment by skalyan91** [comment]
I'm not that experienced with shell scripting; could you have a go? Thanks.

**Comment by schemar** [comment]
@skalyan91 please check the latest version `v1.0.2`, it should be fixed.

**Comment by skalyan91** [comment]
The color has changed; but it should be darker (comparable to the corresponding color in the plain Arc theme).

**Comment by schemar** [comment]
OK, which color do you think it should have from the Solarized palette?

**Comment by skalyan91** [comment]
I would suggest Base02, the same color as the titlebar itself.

**Comment by schemar** [comment]
This should finally be fixed in 57bb002334b18a56e2912c1f550995e243d6b5b5
