### ISSUE TITLE
GNOME sliders missing in Shell theme

### ISSUE THREAD

**Issue by fizzy-drinks** [schemar/solarc-theme#21]
I'm currently running GNOME 3 on Manjaro and I've installed the SolArc themes. While the application theme works great, setting the shell theme to either SolArc theme makes the sliders (such as the volume and screen brightness sliders) disappear completely.

**Comment by schemar** [comment]
Hm, there were no changes in upstream ([Arc](https://github.com/horst3180/arc-theme)). Does the problem only occur with SolArc, or with Arc as well?
Does it completely disappear or does the *color* make it invisible?

**Comment by fizzy-drinks** [comment]
Nope, it completely disappears, and only on SolArc. The images below are all at 100% volume.

Arc:

![image](https://user-images.githubusercontent.com/6524870/50907130-c2646300-140d-11e9-948f-73985f4216f8.png)

Arc-dark:

![image](https://user-images.githubusercontent.com/6524870/50907166-dc05aa80-140d-11e9-84cc-895ae3dcd4b3.png)

SolArc:

![image](https://user-images.githubusercontent.com/6524870/50907069-a19c0d80-140d-11e9-92fb-3a9249733120.png)

It looks the same whether I set Shell to SolArc or SolArc-dark. Below is the full GNOME tweak config. Changing anything but Shell does not help:

![image](https://user-images.githubusercontent.com/6524870/50907295-29821780-140e-11e9-883f-09c03e712825.png)

I'm on Manjaro 17 with the following package versions:

    local/gnome-shell 1:3.30.2-1 (gnome)
    local/arc-gtk-theme 20181022-1
    local/gtk-theme-solarc-git 707.800c997-1

If you need any other package versions or info please let me know.

**Comment by fizzy-drinks** [comment]
I should add, this is true for all slider-type GTK components in all apps.

**Comment by schemar** [comment]
Did you set Aplicativos and Shell to SolArc-Dark?

**Comment by fizzy-drinks** [comment]
I face the issue when I set Shell to SolArc or SolArc-Dark. This is why I'm using the base Arc theme as a workaround.

Setting Applications to SolArc-Dark is not a problem AFAIK. Everything so far looks great.

**Comment by schemar** [comment]
Hm 🤔 Can you identify which color Arc uses for the slider and the background of the slider?
And if you can check which color we use as replacements for both? Maybe they are accidentally the same 🧐

**Comment by fizzy-drinks** [comment]
How can I check this? Not sure where to start looking

**Comment by schemar** [comment]
You would make screenshots and check the colors there to see what is used.
In the file [solarize.sh](https://github.com/schemar/solarc-theme/blob/master/solarize.sh) you can check where they are used and how they are replaced. Basically, SolArc works by using [Arc](https://github.com/horst3180/arc-theme) and replacing all the colors via the [solarize.sh](https://github.com/schemar/solarc-theme/blob/master/solarize.sh) script.

**Comment by trinaldi** [comment]
What is the value of `-barlevel-active-background-color` under the class `.slider` at the file `/usr/share/themes/SolArc/gnome-shell/gnome-shell.css`?

It's working perfectly for me.

**Comment by Omnikron13** [comment]
This is fixed in the current codebase.
