### ISSUE TITLE
GTK2 theme matching GTK3

### ISSUE THREAD

**Issue by Omnikron13** [schemar/solarc-theme#24]
I've reworked the GTK2 theme to match the GTK3 theme (as best as seems possible) in my fork:

![gtk2](https://user-images.githubusercontent.com/2133262/56334650-1d39f300-6191-11e9-868d-72f726fb85f9.png)

...however to make things easier to work with I replaced the ARC_COLORS & SOLARIZED_COLORS arrays with a single associative array (this would make BASH 4.0+ a hard dependency). I don't know if this is acceptable to you upstream, but if it is I can try and put together a PR.

**Comment by schemar** [comment]
Absolutely, I would love that!
Would you consider becoming an official maintainer of this repository @Omnikron13 ? You could push your changes directly.
I don't have much time any more to maintain this 😞

**Comment by Omnikron13** [comment]
Refactor & tweaks all bundled up in PR #25. As for making me a maintainer, I guess you can if you want, though I'd still have to make and test my changes in my fork first as I don't know how to rebuild the themes from a clean upstream otherwise. =P

**Comment by schemar** [comment]
Well, you can update *this* repository to cleanly build from upstream! 💪
