### ISSUE TITLE
Dropdown should have solarized colours

### ISSUE THREAD

**Issue by schemar** [schemar/solarc-theme#3]
gtk-2.0 only.

The dropdown in the preview window should not be dark grey, but instead a light colour, e.g. `Base00`, or dark blue (`Base03`).

![screenshot](https://i.imgur.com/aehgutg.png)

**Comment by Omnikron13** [comment]
Pretty sure this is an upstream bug.

One part of gtk-2.0/assets-dark.svg (ln 993) uses `#3e4351` instead of `#3e4350` as it seems the gtkrc-dark file is suggesting. This means that solarize.sh isn't able to correctly replace it.

**Comment by Omnikron13** [comment]
Here's a workaround PR #23, though I'm gonna open an issue upstream which would probably be the cleaner solution.

**Comment by schemar** [comment]
Thanks! For now this is fixed in #23 💪
