### ISSUE TITLE
Check components of 20190917 branch

### ISSUE THREAD

**Issue by Omnikron13** [schemar/solarc-theme#33]
Branch re-bases onto the 20190917 release of the upstream Arc theme.
Must check components:

- ~~GTK2~~
- ~~GTK3~~
- ~~xfwm~~
- ~~Gnome shell~~
- ~~Cinnamon~~
- ~~Metacity~~
- Unity
- ~~Plank~~
- ~~Openbox~~

**Comment by Omnikron13** [comment]
Unity not tested as Unity8 doesn't have a stable desktop release, and I believe is only intended for Ubuntu systems which I don't have a current box or VM for atm. Will probably return to this only if/when there is a new stable release.

**Comment by schemar** [comment]
Thank you @Omnikron13 !
