### ISSUE TITLE
Solarc interferes with Arc. Solution inside.

### ISSUE THREAD

**Issue by tristan957** [schemar/solarc-theme#6]
- Distribution: Solus
- Desktop environment: Budgie
- GTK+ 3 version: 3.18
- Arc version (commit):

The file arc-theme-upgrade is incompatible if you have the Arc theme installed because the two files use the same name. The arc-theme-upgrade file needs to be looked at. Looks like it hasn't been touched as of yet which is understandable since this a new theme. I looked at the file and I think I corrected everything. I don't use git so I don't know how to commit but here is the file:

[solarc-theme-upgrade.zip](https://github.com/apheleia/solarc-theme/files/397771/solarc-theme-upgrade.zip)

**Comment by schemar** [comment]
Thanks, I will give it a look :+1:

**Comment by schemar** [comment]
I added it, thanks @tristan957!

**Comment by tristan957** [comment]
It didn't take much of my time but glad I could help you out.
