### ISSUE TITLE
Gnome shell theme dropdown colors incorrect

### ISSUE THREAD

**Issue by jlnxr** [schemar/solarc-theme#8]
- Distribution: Debian
- Desktop environment: Gnome 3.14
- GTK+ 3 version: 3.14
- Arc version (commit): 573

As shown here: 

https://imgur.com/a/pnLBk

The color of the gnome shell theme drop downs remains dark gray instead of the usual solarized base ( how the taskbar is colored)

**Comment by schemar** [comment]
Thanks for the report, I will look into this.

**Comment by schemar** [comment]
This should be fixed with the latest version, can you please check?
