### ISSUE TITLE
Won't build on Solus

### ISSUE THREAD

**Issue by tristan957** [schemar/solarc-theme#9]
- Distribution: Solus
- Desktop environment: Budgie
- GTK+ 3 version: 3.20
- Arc version (commit):

The theme won't build correctly at the autogen part. I receive these lines after attempting to run the code.

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

I'm fairly certain that I have all the prerequisites installed

**Comment by schemar** [comment]
Hey @tristan957,

I am afraid this is an issue with the general arc theme: https://github.com/horst3180/arc-theme
You will get more help there. SolArc is only about adapting the colours of the arc theme.

Are you sure GNU m4 is available on your platform?

**Comment by tristan957** [comment]
Yep I just needed to install m4. Thanks!
